# Generated by Django 5.2.7 on 2025-10-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('platform', models.CharField(choices=[('Zoom', 'Zoom'), ('Google Meet', 'Google Meet')], max_length=20)),
                ('link', models.URLField()),
            ],
        ),
    ]
