# Generated by Django 5.2.7 on 2025-10-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de ingreso de la cita'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida de la cita'),
        ),
    ]
