# Generated by Django 5.2.7 on 2025-10-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0002_remove_appointment_time_appointment_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pendiente'), ('accepted', 'aceptada'), ('missed', 'perdida')], default='pending', max_length=10, verbose_name='Estado'),
        ),
    ]
