# Generated by Django 5.1.5 on 2025-10-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appi', '0003_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
